package br.com.converstore.db.entity;
// Generated 11/04/2017 17:48:48 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", schema = "public")
public class Categoria implements java.io.Serializable {

	private int cdcategoria;
	private String dscategoria;
	private Date dtcadastro;
	private Integer cddepartamento;

	public Categoria() {
	}

	public Categoria(int cdcategoria) {
		this.cdcategoria = cdcategoria;
	}

	public Categoria(int cdcategoria, String dscategoria, Date dtcadastro, Integer cddepartamento) {
		this.cdcategoria = cdcategoria;
		this.dscategoria = dscategoria;
		this.dtcadastro = dtcadastro;
		this.cddepartamento = cddepartamento;
	}

	@Id

	@Column(name = "cdcategoria", unique = true, nullable = false)
	public int getCdcategoria() {
		return this.cdcategoria;
	}

	public void setCdcategoria(int cdcategoria) {
		this.cdcategoria = cdcategoria;
	}

	@Column(name = "dscategoria", length = 100)
	public String getDscategoria() {
		return this.dscategoria;
	}

	public void setDscategoria(String dscategoria) {
		this.dscategoria = dscategoria;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtcadastro", length = 13)
	public Date getDtcadastro() {
		return this.dtcadastro;
	}

	public void setDtcadastro(Date dtcadastro) {
		this.dtcadastro = dtcadastro;
	}

	@Column(name = "cddepartamento")
	public Integer getCddepartamento() {
		return this.cddepartamento;
	}

	public void setCddepartamento(Integer cddepartamento) {
		this.cddepartamento = cddepartamento;
	}

}
