package br.com.converstore.db.entity;
// Generated 11/04/2017 17:48:48 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name = "produtos", schema = "public")
public class Produtos implements java.io.Serializable {

	private int cdproduto;
	private String dsproduto;
	private Date dtcadastro;
	private BigDecimal altura;
	private BigDecimal largura;
	private Integer embalagemfabricante;
	private Integer embalagemfabricantealternativa;
	private Integer embalagemvenda;

	public Produtos() {
	}

	public Produtos(int cdproduto) {
		this.cdproduto = cdproduto;
	}

	public Produtos(int cdproduto, String dsproduto, Date dtcadastro, BigDecimal altura, BigDecimal largura,
			Integer embalagemfabricante, Integer embalagemfabricantealternativa, Integer embalagemvenda) {
		this.cdproduto = cdproduto;
		this.dsproduto = dsproduto;
		this.dtcadastro = dtcadastro;
		this.altura = altura;
		this.largura = largura;
		this.embalagemfabricante = embalagemfabricante;
		this.embalagemfabricantealternativa = embalagemfabricantealternativa;
		this.embalagemvenda = embalagemvenda;
	}

	@Id

	@Column(name = "cdproduto", unique = true, nullable = false)
	public int getCdproduto() {
		return this.cdproduto;
	}

	public void setCdproduto(int cdproduto) {
		this.cdproduto = cdproduto;
	}

	@Column(name = "dsproduto", length = 200)
	public String getDsproduto() {
		return this.dsproduto;
	}

	public void setDsproduto(String dsproduto) {
		this.dsproduto = dsproduto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dtcadastro", length = 13)
	public Date getDtcadastro() {
		return this.dtcadastro;
	}

	public void setDtcadastro(Date dtcadastro) {
		this.dtcadastro = dtcadastro;
	}

	@Column(name = "altura", precision = 131089, scale = 0)
	public BigDecimal getAltura() {
		return this.altura;
	}

	public void setAltura(BigDecimal altura) {
		this.altura = altura;
	}

	@Column(name = "largura", precision = 131089, scale = 0)
	public BigDecimal getLargura() {
		return this.largura;
	}

	public void setLargura(BigDecimal largura) {
		this.largura = largura;
	}

	@Column(name = "embalagemfabricante")
	public Integer getEmbalagemfabricante() {
		return this.embalagemfabricante;
	}

	public void setEmbalagemfabricante(Integer embalagemfabricante) {
		this.embalagemfabricante = embalagemfabricante;
	}

	@Column(name = "embalagemfabricantealternativa")
	public Integer getEmbalagemfabricantealternativa() {
		return this.embalagemfabricantealternativa;
	}

	public void setEmbalagemfabricantealternativa(Integer embalagemfabricantealternativa) {
		this.embalagemfabricantealternativa = embalagemfabricantealternativa;
	}

	@Column(name = "embalagemvenda")
	public Integer getEmbalagemvenda() {
		return this.embalagemvenda;
	}

	public void setEmbalagemvenda(Integer embalagemvenda) {
		this.embalagemvenda = embalagemvenda;
	}

}
